### PR TITLE
Add wslbridge-backend path from command

### PR DESCRIPTION
**Pull request by Biswa96**
I've added the `-p` option to add wslbridge-backend path. With that option, the backend find can be put in anywhere.

### CODE REVIEW

**Comment by Biswa96** [comment]
Please reply if I've to edit something small.

**Comment by rprichard** [comment]
You already closed https://github.com/rprichard/wslbridge/issues/23?

I don't think I understand why this option is needed. You've run into a situation where the two files can't be in the same directory, I guess?

I'd prefer something more descriptive than `-p`. Maybe `--backend <PATH>`.

It looks like your `-p` option accepts a Windows-style path rather than a WSL-style path. The Windows-to-WSL path conversion has had some issues, so if there's an option to specify the backend path, maybe it ought to be a WSL-style path to sidestep those issues.

**Comment by Biswa96** [comment]
With this option, users have no restriction to place both file in same directory, they can place those anywhere. For the `-p` option, I follow your previous one alphabetic options.  To convert the path you've use that function, so do I.
I tried with both 1. Place backend and  frontend in same path. 2. Use `-p` option with only the directory of backend and both works.

**Comment by Biswa96** [comment]
I've tried to compile the backend as statically links. But some errors occur. See this https://github.com/mintty/mintty/issues/500#comment-368812621

**Comment by Biswa96** [comment]
Ok wait sometime, I'll fix that.

**Comment by Biswa96** [comment]
@rprichard Sorry for the delay. I've exams. Try the fix.

**Comment by Biswa96** [comment]
Any feedback?

**Comment by Biswa96** [comment]
Is there any problem?

**Comment by Biswa96** [comment]
May you please accept these changes? This helps in wsltty.appx project.

**Comment by rprichard** [comment]
Why does the wsltty.appx project need the flag?

**Comment by Biswa96** [comment]
Because in UWP environment the backend cannot be executed. So it need to copied in LocalAppData. And with that option I can execute backend from that path.

**Comment by Biswa96** [comment]
🙇

**Comment by rprichard** [comment]
Ok, that makes sense. I'll try to look at the change soon. Maybe I'll just add a `--backend` option.

**Comment by Biswa96** [comment]
I had added that option I second commit.

**Comment by rprichard** [comment]
Not necessary. I already have this behavior written. I'll push it within a day:
```
  --backend BACKEND
                Overrides the default path to wslbridge-backend. BACKEND is a
                Cygwin-style path (not a WSL path).
```
It takes a path to the file rather than a path to a directory containing the file. I assume that's not an issue.

**Comment by Biswa96** [comment]
Is it then take `cygdrive/c` not `C:\`? But in UWP API that although will be in Windows style.

**Comment by rprichard** [comment]
It's just the normal Cygwin rules. `/cygdrive/c/foo` is OK, as is `C:\foo`. `/foo` and `\foo`, however, will refer to `C:\path\to\cygwin\foo`, whereas the ordinary Windows rules would interpret it as drive-relative, e.g. `C:\foo`.

**Comment by Biswa96** [comment]
Should I close this PR?

**Comment by rprichard** [comment]
Yes, please close it.

**Comment by Biswa96** [comment]
May you list all the options of frontend and backend in readme file?

**Comment by Biswa96** [comment]
When do you release this current feature?

**Pull request closed without merging**
